// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.0
// source: cmd/proto/player.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PlayerCreateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Email         string                 `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	Password      string                 `protobuf:"bytes,3,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlayerCreateRequest) Reset() {
	*x = PlayerCreateRequest{}
	mi := &file_cmd_proto_player_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlayerCreateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerCreateRequest) ProtoMessage() {}

func (x *PlayerCreateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cmd_proto_player_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerCreateRequest.ProtoReflect.Descriptor instead.
func (*PlayerCreateRequest) Descriptor() ([]byte, []int) {
	return file_cmd_proto_player_proto_rawDescGZIP(), []int{0}
}

func (x *PlayerCreateRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *PlayerCreateRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *PlayerCreateRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type PlayerCreateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlayerCreateResponse) Reset() {
	*x = PlayerCreateResponse{}
	mi := &file_cmd_proto_player_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlayerCreateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerCreateResponse) ProtoMessage() {}

func (x *PlayerCreateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cmd_proto_player_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerCreateResponse.ProtoReflect.Descriptor instead.
func (*PlayerCreateResponse) Descriptor() ([]byte, []int) {
	return file_cmd_proto_player_proto_rawDescGZIP(), []int{1}
}

func (x *PlayerCreateResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type PlayerLoginRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlayerLoginRequest) Reset() {
	*x = PlayerLoginRequest{}
	mi := &file_cmd_proto_player_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlayerLoginRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerLoginRequest) ProtoMessage() {}

func (x *PlayerLoginRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cmd_proto_player_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerLoginRequest.ProtoReflect.Descriptor instead.
func (*PlayerLoginRequest) Descriptor() ([]byte, []int) {
	return file_cmd_proto_player_proto_rawDescGZIP(), []int{2}
}

func (x *PlayerLoginRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *PlayerLoginRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type PlayerLoginResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	ExpiresAt     int64                  `protobuf:"varint,2,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlayerLoginResponse) Reset() {
	*x = PlayerLoginResponse{}
	mi := &file_cmd_proto_player_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlayerLoginResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerLoginResponse) ProtoMessage() {}

func (x *PlayerLoginResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cmd_proto_player_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerLoginResponse.ProtoReflect.Descriptor instead.
func (*PlayerLoginResponse) Descriptor() ([]byte, []int) {
	return file_cmd_proto_player_proto_rawDescGZIP(), []int{3}
}

func (x *PlayerLoginResponse) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *PlayerLoginResponse) GetExpiresAt() int64 {
	if x != nil {
		return x.ExpiresAt
	}
	return 0
}

var File_cmd_proto_player_proto protoreflect.FileDescriptor

const file_cmd_proto_player_proto_rawDesc = "" +
	"\n" +
	"\x16cmd/proto/player.proto\x12\x10playerservice.v1\"c\n" +
	"\x13PlayerCreateRequest\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12\x14\n" +
	"\x05email\x18\x02 \x01(\tR\x05email\x12\x1a\n" +
	"\bpassword\x18\x03 \x01(\tR\bpassword\"&\n" +
	"\x14PlayerCreateResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"L\n" +
	"\x12PlayerLoginRequest\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\"J\n" +
	"\x13PlayerLoginResponse\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\x12\x1d\n" +
	"\n" +
	"expires_at\x18\x02 \x01(\x03R\texpiresAt2\xbe\x01\n" +
	"\rPlayerService\x12W\n" +
	"\x06Create\x12%.playerservice.v1.PlayerCreateRequest\x1a&.playerservice.v1.PlayerCreateResponse\x12T\n" +
	"\x05Login\x12$.playerservice.v1.PlayerLoginRequest\x1a%.playerservice.v1.PlayerLoginResponseB\x1dZ\x1bmatchmaking/cmd/proto;protob\x06proto3"

var (
	file_cmd_proto_player_proto_rawDescOnce sync.Once
	file_cmd_proto_player_proto_rawDescData []byte
)

func file_cmd_proto_player_proto_rawDescGZIP() []byte {
	file_cmd_proto_player_proto_rawDescOnce.Do(func() {
		file_cmd_proto_player_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_cmd_proto_player_proto_rawDesc), len(file_cmd_proto_player_proto_rawDesc)))
	})
	return file_cmd_proto_player_proto_rawDescData
}

var file_cmd_proto_player_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_cmd_proto_player_proto_goTypes = []any{
	(*PlayerCreateRequest)(nil),  // 0: playerservice.v1.PlayerCreateRequest
	(*PlayerCreateResponse)(nil), // 1: playerservice.v1.PlayerCreateResponse
	(*PlayerLoginRequest)(nil),   // 2: playerservice.v1.PlayerLoginRequest
	(*PlayerLoginResponse)(nil),  // 3: playerservice.v1.PlayerLoginResponse
}
var file_cmd_proto_player_proto_depIdxs = []int32{
	0, // 0: playerservice.v1.PlayerService.Create:input_type -> playerservice.v1.PlayerCreateRequest
	2, // 1: playerservice.v1.PlayerService.Login:input_type -> playerservice.v1.PlayerLoginRequest
	1, // 2: playerservice.v1.PlayerService.Create:output_type -> playerservice.v1.PlayerCreateResponse
	3, // 3: playerservice.v1.PlayerService.Login:output_type -> playerservice.v1.PlayerLoginResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_cmd_proto_player_proto_init() }
func file_cmd_proto_player_proto_init() {
	if File_cmd_proto_player_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_cmd_proto_player_proto_rawDesc), len(file_cmd_proto_player_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_cmd_proto_player_proto_goTypes,
		DependencyIndexes: file_cmd_proto_player_proto_depIdxs,
		MessageInfos:      file_cmd_proto_player_proto_msgTypes,
	}.Build()
	File_cmd_proto_player_proto = out.File
	file_cmd_proto_player_proto_goTypes = nil
	file_cmd_proto_player_proto_depIdxs = nil
}
