// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.0
// source: cmd/proto/queue.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type QueueEvent_Type int32

const (
	QueueEvent_QUEUED      QueueEvent_Type = 0
	QueueEvent_MATCH_FOUND QueueEvent_Type = 1
	QueueEvent_TIMEOUT     QueueEvent_Type = 2
	QueueEvent_CANCELLED   QueueEvent_Type = 3
)

// Enum value maps for QueueEvent_Type.
var (
	QueueEvent_Type_name = map[int32]string{
		0: "QUEUED",
		1: "MATCH_FOUND",
		2: "TIMEOUT",
		3: "CANCELLED",
	}
	QueueEvent_Type_value = map[string]int32{
		"QUEUED":      0,
		"MATCH_FOUND": 1,
		"TIMEOUT":     2,
		"CANCELLED":   3,
	}
)

func (x QueueEvent_Type) Enum() *QueueEvent_Type {
	p := new(QueueEvent_Type)
	*p = x
	return p
}

func (x QueueEvent_Type) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (QueueEvent_Type) Descriptor() protoreflect.EnumDescriptor {
	return file_cmd_proto_queue_proto_enumTypes[0].Descriptor()
}

func (QueueEvent_Type) Type() protoreflect.EnumType {
	return &file_cmd_proto_queue_proto_enumTypes[0]
}

func (x QueueEvent_Type) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use QueueEvent_Type.Descriptor instead.
func (QueueEvent_Type) EnumDescriptor() ([]byte, []int) {
	return file_cmd_proto_queue_proto_rawDescGZIP(), []int{2, 0}
}

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_cmd_proto_queue_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_cmd_proto_queue_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_cmd_proto_queue_proto_rawDescGZIP(), []int{0}
}

type QueueRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Region        string                 `protobuf:"bytes,1,opt,name=region,proto3" json:"region,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueueRequest) Reset() {
	*x = QueueRequest{}
	mi := &file_cmd_proto_queue_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueueRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueueRequest) ProtoMessage() {}

func (x *QueueRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cmd_proto_queue_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueueRequest.ProtoReflect.Descriptor instead.
func (*QueueRequest) Descriptor() ([]byte, []int) {
	return file_cmd_proto_queue_proto_rawDescGZIP(), []int{1}
}

func (x *QueueRequest) GetRegion() string {
	if x != nil {
		return x.Region
	}
	return ""
}

type QueueEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          QueueEvent_Type        `protobuf:"varint,1,opt,name=type,proto3,enum=queue.QueueEvent_Type" json:"type,omitempty"`
	MatchId       string                 `protobuf:"bytes,2,opt,name=match_id,json=matchId,proto3" json:"match_id,omitempty"`
	GameId        string                 `protobuf:"bytes,3,opt,name=game_id,json=gameId,proto3" json:"game_id,omitempty"`
	OpponentId    string                 `protobuf:"bytes,4,opt,name=opponent_id,json=opponentId,proto3" json:"opponent_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueueEvent) Reset() {
	*x = QueueEvent{}
	mi := &file_cmd_proto_queue_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueueEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueueEvent) ProtoMessage() {}

func (x *QueueEvent) ProtoReflect() protoreflect.Message {
	mi := &file_cmd_proto_queue_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueueEvent.ProtoReflect.Descriptor instead.
func (*QueueEvent) Descriptor() ([]byte, []int) {
	return file_cmd_proto_queue_proto_rawDescGZIP(), []int{2}
}

func (x *QueueEvent) GetType() QueueEvent_Type {
	if x != nil {
		return x.Type
	}
	return QueueEvent_QUEUED
}

func (x *QueueEvent) GetMatchId() string {
	if x != nil {
		return x.MatchId
	}
	return ""
}

func (x *QueueEvent) GetGameId() string {
	if x != nil {
		return x.GameId
	}
	return ""
}

func (x *QueueEvent) GetOpponentId() string {
	if x != nil {
		return x.OpponentId
	}
	return ""
}

var File_cmd_proto_queue_proto protoreflect.FileDescriptor

const file_cmd_proto_queue_proto_rawDesc = "" +
	"\n" +
	"\x15cmd/proto/queue.proto\x12\x05queue\"\a\n" +
	"\x05Empty\"&\n" +
	"\fQueueRequest\x12\x16\n" +
	"\x06region\x18\x01 \x01(\tR\x06region\"\xce\x01\n" +
	"\n" +
	"QueueEvent\x12*\n" +
	"\x04type\x18\x01 \x01(\x0e2\x16.queue.QueueEvent.TypeR\x04type\x12\x19\n" +
	"\bmatch_id\x18\x02 \x01(\tR\amatchId\x12\x17\n" +
	"\agame_id\x18\x03 \x01(\tR\x06gameId\x12\x1f\n" +
	"\vopponent_id\x18\x04 \x01(\tR\n" +
	"opponentId\"?\n" +
	"\x04Type\x12\n" +
	"\n" +
	"\x06QUEUED\x10\x00\x12\x0f\n" +
	"\vMATCH_FOUND\x10\x01\x12\v\n" +
	"\aTIMEOUT\x10\x02\x12\r\n" +
	"\tCANCELLED\x10\x032r\n" +
	"\x12MatchmakingService\x121\n" +
	"\x05Queue\x12\x13.queue.QueueRequest\x1a\x11.queue.QueueEvent0\x01\x12)\n" +
	"\vCancelQueue\x12\f.queue.Empty\x1a\f.queue.EmptyB#Z!matchmaking/cmd/queue/proto;protob\x06proto3"

var (
	file_cmd_proto_queue_proto_rawDescOnce sync.Once
	file_cmd_proto_queue_proto_rawDescData []byte
)

func file_cmd_proto_queue_proto_rawDescGZIP() []byte {
	file_cmd_proto_queue_proto_rawDescOnce.Do(func() {
		file_cmd_proto_queue_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_cmd_proto_queue_proto_rawDesc), len(file_cmd_proto_queue_proto_rawDesc)))
	})
	return file_cmd_proto_queue_proto_rawDescData
}

var file_cmd_proto_queue_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_cmd_proto_queue_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_cmd_proto_queue_proto_goTypes = []any{
	(QueueEvent_Type)(0), // 0: queue.QueueEvent.Type
	(*Empty)(nil),        // 1: queue.Empty
	(*QueueRequest)(nil), // 2: queue.QueueRequest
	(*QueueEvent)(nil),   // 3: queue.QueueEvent
}
var file_cmd_proto_queue_proto_depIdxs = []int32{
	0, // 0: queue.QueueEvent.type:type_name -> queue.QueueEvent.Type
	2, // 1: queue.MatchmakingService.Queue:input_type -> queue.QueueRequest
	1, // 2: queue.MatchmakingService.CancelQueue:input_type -> queue.Empty
	3, // 3: queue.MatchmakingService.Queue:output_type -> queue.QueueEvent
	1, // 4: queue.MatchmakingService.CancelQueue:output_type -> queue.Empty
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_cmd_proto_queue_proto_init() }
func file_cmd_proto_queue_proto_init() {
	if File_cmd_proto_queue_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_cmd_proto_queue_proto_rawDesc), len(file_cmd_proto_queue_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_cmd_proto_queue_proto_goTypes,
		DependencyIndexes: file_cmd_proto_queue_proto_depIdxs,
		EnumInfos:         file_cmd_proto_queue_proto_enumTypes,
		MessageInfos:      file_cmd_proto_queue_proto_msgTypes,
	}.Build()
	File_cmd_proto_queue_proto = out.File
	file_cmd_proto_queue_proto_goTypes = nil
	file_cmd_proto_queue_proto_depIdxs = nil
}
